apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycache-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycache
  template:
    metadata:
      labels:
        app: mycache
    spec:
      containers:
        - name: mycache
          image: mycache:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP