apiVersion: v1
kind: Service
metadata:
  name: mycache-service
spec:
  type: NodePort
  selector:
    app: mycache
  ports:
    - name: api
      protocol: TCP
      port: 9999       # Service 内部端口（ClusterIP）
      targetPort: 9999 # 容器内的缓存查询端口
      nodePort: 30001  # 节点上暴露的端口，可自定义（30000-32767）

